import type {NextPage} from 'next'
import Head from 'next/head'
import ProceedButton from "src/components/ProceedButton";
import Header from "../src/components/Header";
import Tab from "../src/components/Tab";

const Home: NextPage = () => {
    return (
        <div style={{backgroundColor: "#F5F7F8", minHeight: "100vh"}}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>
            <ProceedButton>Далее</ProceedButton>
        </div>
    )
}

export default Home
